### ISSUE TITLE
Allow target commands to use run element

### ISSUE THREAD

**Issue by lstephen** [lstephen/construi#11]
e.g.,
```
target:
  build:
    run:
      - cmd1
      - cmd2
  release:
    run: construi/release/script.sh
```

While not useful on it's own it will be useful when we wish to allow specifying other parameters for the build (e.g., a different image - #5)
