### ISSUE TITLE
Allow setting of shell

### ISSUE THREAD

**Issue by lstephen** [lstephen/construi#126]
For a target allow setting a 'shell'. This avoids long lines of commands starting with /bin/sh -c

Example
```
targets:
  some_env_stuff:
    shell: /bin/sh -c
    run:
      - echo $AN_ENV_VAR
      - cat VERSION > some_redirected_output
```

This should run commands as `/bin/sh -c "... command ..."`
