### ISSUE TITLE
Dependencies between targets

### ISSUE THREAD

**Issue by lstephen** [lstephen/construi#9]
Allow dependencies between targets

e.g.,

```
targets:
  setup:
    - bundle install --path=vendor/bundle

  build:
    depends_on:
      - setup
    commands:
      - bundle exec rake install
```
